### ISSUE TITLE
How to use/compile in Readme.md

### ISSUE THREAD

**Issue by crutchcorn** [xorprojects/Auto-Virtual-Host#1]
Please make it so that even the amazingly dumb @crutchcorn could figure it out. ;) KTHXBAI

**Comment by danielhickman** [comment]
It's done using Ruby which you need installed first (`apt-get install ruby`) and then you run it using ruby (`ruby programName.rb`). I'll have to make it more clear though.

**Comment by crutchcorn** [comment]
Thank you
